# Generated by Django 5.2.3 on 2025-07-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nid_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
