# Generated by Django 5.2.3 on 2025-06-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='', help_text='Enter the icon class from font awesome', max_length=255),
            preserve_default=False,
        ),
    ]
