# Generated by Django 5.2.3 on 2025-06-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_service_image_service_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='Enter the icon class from font awesome', max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
