# Generated by Django 5.2.3 on 2025-06-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_about_alter_service_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Features',
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'ordering': ['id'], 'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
    ]
