# Generated by Django 5.2.3 on 2025-06-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_rename_about_features_alter_features_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=255)),
                ('from_station', models.CharField(max_length=255)),
                ('to_station', models.CharField(max_length=255)),
                ('time', models.TimeField(help_text='Enter the time in 24 hour format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Train Schedule',
                'verbose_name_plural': 'Train Schedules',
                'ordering': ['id'],
            },
        ),
    ]
