# Generated by Django 5.2.3 on 2025-06-29 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_trainschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Update Category',
                'verbose_name_plural': 'Update Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='updates/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='cms.updatecategory')),
            ],
            options={
                'verbose_name': 'Update',
                'verbose_name_plural': 'Updates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='cms_updates_created_c107b9_idx'), models.Index(fields=['category'], name='cms_updates_categor_4689b6_idx')],
            },
        ),
    ]
