# Generated by Django 5.2.3 on 2025-07-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_updatecategory_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updates',
            options={'ordering': ['created_at'], 'verbose_name': 'Update', 'verbose_name_plural': 'Updates'},
        ),
    ]
